### ISSUE TITLE
Failed to parse base64 encoded SVG.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [zmoazeni/csscss#18]
The rule, cleaned up a little, was as follows. I was simply inlining an icon.

``` css
.class.anotherClass > section {
  background: transparent url('data:image/svg+xml;base64,IMGDATAGOESHERE') no-repeat 4px 4px;
}
```
