### ISSUE TITLE
Incorrectly reporting duplicate declarations when using media queries

### ISSUE THREAD

**Issue by jjenzz** [zmoazeni/csscss#45]
I have something similar to the following:

``` css
@media (min-width: 30em) {
  .m-label {
    display: block;
  }
}

/* because less than IE9 
 * doesn't support media queries */
.lt-ie9 .m-label {
  display: block;
}
```

Although they are sharing the same declaration, there is no way around that as they are only sharing it if the media query applies. 

Would it make more sense for the parser to report duplicated declarations outside media queries separately from those inside media queries?
