### ISSUE TITLE
Incorrectly reporting duplicate declarations when using @font-face

### ISSUE THREAD

**Issue by jjenzz** [zmoazeni/csscss#49]
When using something similar to the following:

``` css
@font-face {
  font-family: 'Museo Sans Rounded';
  src: url('../fonts/museosansrounded-300-mmm.eot');
  src: url('../fonts/museosansrounded-300-mmm.eot?#iefix') format('embedded-opentype'),
       url('../fonts/museosansrounded-300-mmm.woff') format('woff'),
       url('../fonts/museosansrounded-300-mmm.ttf') format('truetype'),
       url('../fonts/museosansrounded-700-mmm.svg#museo') format('svg');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'Museo Sans Rounded';
  src: url('../fonts/museosansrounded-500-mmm.eot');
  src: url('../fonts/museosansrounded-500-mmm.eot?#iefix') format('embedded-opentype'),
       url('../fonts/museosansrounded-500-mmm.woff') format('woff'),
       url('../fonts/museosansrounded-500-mmm.ttf') format('truetype'),
       url('../fonts/museosansrounded-700-mmm.svg#museo') format('svg');
  font-weight: 500;
  font-style: normal;
}

.whatever {
  font-family: 'Museo Sans Rounded';
  font-weight: 300;
}
```

`csscss -n 2 -v /path/to/file.css` would report that `{@font-face} AND {.whatever} share 2 rules`. Yes, they do, but for necessary reasons.
